# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 47e3cedf32c17e444ec0fe32369498725b6c57dd3ce636dfb86844ee5845816d9ff68c8a5291389166f3c69c76759e290229789e8cea3fd900dd6b6285340fcf

test:
  secret_key_base: 607509aa6c99f6b29807d185b194e1a4bb30d7c0a0f3a19978f50915eaf4037434d7cb7e359373645a94af4e65ab1744140e64f3b86047bc4cb5ec4999fd65cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
