# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 599bbc25d1f7cdf18921262555646742ea25df32df3fe49dabcf180c68c8326cb254e32bd41b235e0e2b67a37e5af48da9c802a1f3daac3f01fe43dfa848d880

test:
  secret_key_base: d733d5e0e20cbf962d957b8e277fa81c1c3fc1dab99ec557f5cf7842ec9f1fc7512248d57b50f9641e605a03def29ad9a45226426e47bc86165e45c2156230a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
