# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a2d7c657b14700b51b6c91753eb4c6876452996759eaa7e9990fba6a67c3550e663fb17ea5d5c9f6f1ac1502291ebdf5d9e5efa6a46ab24b2eeaa492475a48d9

test:
  secret_key_base: 10f723e1cc2052f8f2ae0d21659acd688f7bf43e17dcf7ddff2c07812ae386b62f4839e15ada89b82fa7f870053e682e49e99023a229eadb5465a706a816e002

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
